name:                strictness-polymorphism
version:             0.1.0.0
github:              "nickmertin/strictness-polymorphism"
license:             BSD3
author:              "Nick Mertin"
maintainer:          "nickmertin@gmail.com"
copyright:           "2020 Nick Mertin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/strictness-polymorphism#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  strictness-polymorphism-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - strictness-polymorphism
